# Deploy front-end build to GitHub Pages
name: Deploy Frontend to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # ou a versão que você usa

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build  # assume que gera a pasta 'dist'

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload build folder
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'  # só a pasta de build

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
